add test collection

diff --git a/.github/workflows/gradle.yaml b/.github/workflows/gradle.yaml
--- a/.github/workflows/gradle.yaml
+++ b/.github/workflows/gradle.yaml
@@ -33,3 +33,11 @@ jobs:
       run: ./gradlew clean test
     - name: Integration Test
       run: ./gradlew integTest
+
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: */build/test-results/*/*.xml    # Path to test results
+          reporter: java-junit        # Format of test results
